train_path: data/processed/train_data.csv
test_path: data/processed/test_features.csv

id_col: company_id
time_col: fiscal_year
target_col: revenue_change

drop_cols:
  - bankruptcy_next_year
  - financial_health_class
