strategy: forecasting_holdout

time_col: fiscal_year
id_col: company_id
target_col: revenue_change

shuffle: false

horizon_years: 1
train_target_years: [2019, 2020]
val_target_years: [2021]
test_target_years: [2022, 2023]
